# commented are part of the API but not yet implemented
export SPACE_LOG_ENABLED=true
export SPACE_LOG_MIN_LEVEL='debug'
# export SPACE_WORKQUEUE_MONGO_URL=
# export SPACE_WORKQUEUE_MONGO_OPLOG_URL=
# export SPACE_WORKQUEUE_COLLECTION_NAME=
# export SPACE_ES_LOG_ENABLED=true
export SPACE_ES_COMMITS_MONGO_URL='mongodb://127.0.0.1:3001/meteor'
# export SPACE_ES_COMMITS_MONGO_OPLOG_URL=
# export SPACE_ES_COMMITS_COLLECTION_NAME=
# export SPACE_ES_COMMITS_PROCESSING_TIMEOUT=
# export SPACE_ES_SNAPSHOTTING_ENABLED=true
# export SPACE_ES_SNAPSHOTTING_FREQUENCY=10
# export SPACE_ES_SNAPSHOTTING_COLLECTION_NAME=
